### ISSUE TITLE
Remove bottom padding on responsive objects

### ISSUE THREAD

**Issue by normade** [normade/knowpo#83]
After adding an embeded object in a post, e.g. a YouTube video, a weird button padding is given by default, e.g. `<div style="padding-bottom: 56.25%;" class="responsive-object">`, see [here](http://normade.pythonanywhere.com/vermietung/vermietung-1/vermietung-uup-0/post-example-title/)
It should be forced to be 0.

**Comment by joba-sprd** [comment]
This padding is not a bug. Its a css "hack" to make videos responsive. 

> http://www.holgerkoenemann.de/ein-vimeo-oder-youtube-video-responsive-einbinden/

I adjusted our css. So it should look responsive now.

**Comment by joba-sprd** [comment]
You can check the changes on feature/design.
